<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CS0-37" name="cs265.AirlineSeatReservationsTest" tests="6" failures="1" timestamp="16 Feb 2018 14:42:57 GMT" time="0.026" errors="0">
  <testcase name="seatsAvailable_test3" time="0.001" classname="cs265.AirlineSeatReservationsTest"/>
  <testcase name="seatsAvailable_test1" time="0.020" classname="cs265.AirlineSeatReservationsTest"/>
  <testcase name="seatsAvailable_test4" time="0.001" classname="cs265.AirlineSeatReservationsTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;false&gt; but was:&lt;true&gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:192)at cs265.AirlineSeatReservationsTest.seatsAvailable_test4(AirlineSeatReservationsTest.java:27)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- seatsAvailable_test4 -->
  <testcase name="seatsAvailable_test2" time="0.001" classname="cs265.AirlineSeatReservationsTest"/>
  <testcase name="seatsAvailable_test5" time="0.002" classname="cs265.AirlineSeatReservationsTest"/>
  <testcase name="seatsAvailable_test6" time="0.001" classname="cs265.AirlineSeatReservationsTest"/>
</testsuite> <!-- cs265.AirlineSeatReservationsTest -->
